
# crime_dict_cp = {
#             'Art. 129, CP': 'Pública condicionada à representação',
#             'Art129CP': 'Pública condicionada à representação',
#             'Art. 129, § 1º, CP': 'Pública condicionada à representação',
#             'Art. 129, § 9º, CP': 'Pública condicionada à representação',
#             'Art. 139, CP': 'Privada',
#             'Art. 140, CP': 'Privada',
#             'Art. 147, CP': 'Pública condicionada à representação',
#             'Art. 148, § único, CP': 'Pública incondicionada',
#             'Art. 150, CP': 'Pública incondicionada',
#             'Art. 150, § 1º, CP': 'Pública incondicionada',
#             'Art. 155, § 4º, CP': 'Pública incondicionada',
#             'Art. 155, § 4º, inciso IV, CP': 'Pública incondicionada',
#             'Art. 163, CP': 'Privada',
#             'Art163CP': 'Privada',
#             'Art. 163, parágrafo único, inciso I, CP': 'Pública incondicionada',
#             'Art. 168, CP': 'Pública incondicionada',
#             'Art. 171, § 2º, incisos I a VI, CP': 'Pública incondicionada',
#             'Art. 180, CP': 'Pública incondicionada',
#             'Art. 186, CP': 'Privada',
#             'Art. 187, CP': 'Privada',
#             'Art. 189, CP': 'Privada',
#             'Art. 214 c/ Art. 223, CP': 'Pública incondicionada',
#             'Art. 216-A, CP': 'Pública condicionada à representação',
#             'Art. 236, CP': 'Pública incondicionada',
#             'Art. 237, CP': 'Pública incondicionada',
#             'Art. 238, CP': 'Pública incondicionada',
#             'Art. 239, CP': 'Pública incondicionada',
#             'Art. 240, CP': 'Pública incondicionada',
#             'Art. 241, CP': 'Pública incondicionada',
#             'Art. 241-A, CP': 'Pública incondicionada',
#             'Art. 241-B, CP': 'Pública incondicionada',
#             'Art. 241-C, CP': 'Pública incondicionada',
#             'Art. 241-D, CP': 'Pública incondicionada',
#             'Art. 241-E, CP': 'Pública incondicionada',
#             'Art. 243, CP': 'Pública incondicionada',
#             'Art. 244-B, CP': 'Pública incondicionada',
#             'Art. 247, CP': 'Pública incondicionada',
#             'Art. 248, CP': 'Pública incondicionada',
#             'Art. 249, CP': 'Pública incondicionada',
#             'Art. 250, CP': 'Pública incondicionada',
#             'Art. 251, CP': 'Pública incondicionada',
#             'Art. 252, CP': 'Pública incondicionada',
#             'Art. 253, CP': 'Pública incondicionada',
#             'Art. 254, CP': 'Pública incondicionada',
#             'Art. 255, CP': 'Pública incondicionada',
#             'Art. 331, CP': 'Pública incondicionada',
#             'Art. 345, CP': 'Pública incondicionada',
#             'Art. 345, §único, CP': 'Privada'}


crime_dict_cp = {
    'art129cp': 'Pública condicionada à representação',
    'art129§1ºcp': 'Pública condicionada à representação',
    'art129§9ºcp': 'Pública condicionada à representação',
    'art139cp': 'Privada',
    'art140cp': 'Privada',
    'art147cp': 'Pública condicionada à representação',
    'art148§únicocp': 'Pública incondicionada',
    'art150cp': 'Pública incondicionada',
    'art150§1ºcp': 'Pública incondicionada',
    'art155§4ºcp': 'Pública incondicionada',
    'art155§4ºincisoivcp': 'Pública incondicionada',
    'art163cp': 'Privada',
    'art163parágrafoúnicoincisoicp': 'Pública incondicionada',
    'art168cp': 'Pública incondicionada',
    'art171§2ºincisosivicp': 'Pública incondicionada',
    'art180cp': 'Pública incondicionada',
    'art186cp': 'Privada',
    'art187cp': 'Privada',
    'art189cp': 'Privada',
    'art214cart223cp': 'Pública incondicionada',
    'art216-acp': 'Pública condicionada à representação',
    'art236cp': 'Pública incondicionada',
    'art237cp': 'Pública incondicionada',
    'art238cp': 'Pública incondicionada',
    'art239cp': 'Pública incondicionada',
    'art240cp': 'Pública incondicionada',
    'art241cp': 'Pública incondicionada',
    'art241-acp': 'Pública incondicionada',
    'art241-bcp': 'Pública incondicionada',
    'art241-ccp': 'Pública incondicionada',
    'art241-dcp': 'Pública incondicionada',
    'art241-ecp': 'Pública incondicionada',
    'art243cp': 'Pública incondicionada',
    'art244-bcp': 'Pública incondicionada',
    'art247cp': 'Pública incondicionada',
    'art248cp': 'Pública incondicionada',
    'art249cp': 'Pública incondicionada',
    'art250cp': 'Pública incondicionada',
    'art251cp': 'Pública incondicionada',
    'art252cp': 'Pública incondicionada',
    'art253cp': 'Pública incondicionada',
    'art254cp': 'Pública incondicionada',
    'art255cp': 'Pública incondicionada',
    'art331cp': 'Pública incondicionada',
    'art345cp': 'Pública incondicionada',
    'art345§únicocp': 'Privada'
}